version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm install yarn -g
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    env_file: .env.dev

