apiVersion: apps/v1
kind: Deployment
metadata:
  name: kody-app
  labels:
    app: kody-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kody-app
      server: web
  template:
    metadata:
      labels:
        app: kody-app
        server: web
    spec:
      containers:
      - image: gcr.io/zeals-sandbox/kody-app:fa2170
        name: kody-app
        ports:
          - containerPort: 3000
        env:
          - name: RAILS_ENV
            value: production
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: kody-secret
                key: secret_key_base
        command: ["bundle", "exec", "rake", "assets:precompile"]
        command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

